name: CI

on: [push, pull_request]

jobs:
  ubuntu-16_04:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.100-rc.2.21458.9"
      - name: Test
        run: dotnet test --verbosity normal
